o = object()

print()
print(o)
print("           *            ")
print("          ***            ")
print("         *****            ")
print("        *******            ")
print("       *********            ")
print()
